ALTER TABLE analytics_checkpoints
  ADD COLUMN IF NOT EXISTS checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS claim_token TEXT,
  ADD COLUMN IF NOT EXISTS captured_snapshot_id BIGINT REFERENCES analytics_snapshots(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS analytics_checkpoints_identity_uq
  ON analytics_checkpoints(checkpoint_id);

CREATE INDEX IF NOT EXISTS analytics_checkpoints_claim_token_idx
  ON analytics_checkpoints(claim_token)
  WHERE claim_token IS NOT NULL;

